<a href="https://colab.research.google.com/github/Nusrat-Rumi/Machines_Learning/blob/main/ML_DL_Academy(class_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
my_list=[1,2,3,4]

In [5]:

arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4])

In [8]:
type(arr)


numpy.ndarray

In [9]:
arr.shape

(4,)

In [11]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
my_list3=[9,10,11,12]
ar=np.array([my_list1,my_list2,my_list3])
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
ar.shape

(3, 4)

In [14]:
ar.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
ar.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [16]:
ar[1,2]

np.int64(7)

In [17]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
ar[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
ar[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [21]:
ar[1:,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [22]:
ar[0:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])