<a href="https://colab.research.google.com/github/Nusrat-Rumi/Machines_Learning/blob/main/ML_DL_Academy(class_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
my_list=[1,2,3,4]

In [5]:

arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4])

In [8]:
type(arr)


numpy.ndarray

In [9]:
arr.shape

(4,)

In [11]:
my_list1=[1,2,3,4]
my_list2=[5,6,7,8]
my_list3=[9,10,11,12]
ar=np.array([my_list1,my_list2,my_list3])
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
ar.shape

(3, 4)

In [14]:
ar.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
ar.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [16]:
ar[1,2]

np.int64(7)

In [17]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
ar[:,:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
ar[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [21]:
ar[1:,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [22]:
ar[0:,0:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [27]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
import numpy as np
arr=np.arange(0,10,step=3) # inbud function
arr

array([0, 3, 6, 9])

In [32]:
np.linspace(0,10,50)



array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])